#server.port=8091
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.jpa.defer-datasource-initialization=true
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=false
#spring.jpa.show-sql=true

#spring.security.user.name=username
#spring.security.user.password=password

server:
  port: 8091
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: sillicon
    url: jdbc:postgresql://localhost:5432/mytest
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: test
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true